spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Apni-Dukaan
    username: postgres
    password: Saransh@2002

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true